import Head from 'next/head'
import { motion } from 'framer-motion'
import { useContext } from 'react'
import { consoleContext } from '../context/Context'




export default function Page({children, pageTitle}) {

  const ctx = useContext(consoleContext)


  return (
    <motion.div
    className={`h-[200px] w-[300px] p-1 ${ctx[0] ? "bg-emerald-500" : "bg-stone-700"} transition-all duration-300 ease-in`} >
      <Head>
        <title>Retro 90s Gameboy | {pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full w-full font-Pixel">

        {!ctx[0] ? 
          
         <OffScreen/>
          :
         <motion.div
          initial={{opacity: 0, y: 4}}
          animate={{opacity: 1, y: 0}}
          transition={{duration: 2, delay: 1.5}}
          className="flex flex-col justify-around items-center h-full">
            {children}
          </motion.div>
        }
        

        
      </main>
        
    </motion.div>
  )
}


const OffScreen = () => {
  return(
    <div className="h-full w-full flex justify-center items-center">

        <h1 className="font-Pixel text-gray-300 text-xs">Oh...it&apos; off again!</h1>
    </div>
  )
}