import Head from 'next/head'
import { motion } from 'framer-motion'
import { useContext } from 'react'
import { deviceContext } from '../context/deviceContext'


export default function Page({children, pageTitle}) {

  const {isOn} = useContext(deviceContext)

  const title = `Retro 90s Gameboy | ${pageTitle}`


  return (
    <div
      className={`h-[200px] w-[300px] ${isOn ? "bg-stone-400" : "bg-stone-700"} transition-all duration-300 ease-in p-1`} >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full w-full font-Pixel">

        {!isOn ? 
          
         <OffScreen/>
          :
         <motion.div
          initial={{opacity: 0, y: 4}}
          animate={{opacity: 1, y: 0}}
          transition={{duration: 2, delay: 1.3}}
          className="flex flex-col justify-around items-center h-full">
            {children}
          </motion.div>
        }
        

        
      </main>
        
    </div>
  )
}


const OffScreen = () => {
  return(
    <div className="h-full w-full flex justify-center items-center bg-indigo-700">

        <h1 className="font-Pixel text-gray-300 text-xs">Oh...it&apos; off again!</h1>
    </div>
  )
}